/**
 * Anthropic-compatible configuration generator
 *
 * Generates configuration for using OCI GenAI with Claude Code
 * via the @acedergren/oci-anthropic-compatible proxy server.
 */

import type { GeneratedConfig, Logger } from '../types.js';
import { writeTextFile } from '../utils/file.js';

/**
 * Generate environment variables content for Anthropic-compatible proxy
 */
function generateEnvContent(config: GeneratedConfig): string {
  const lines: string[] = [
    '# OCI GenAI - Anthropic Compatible Proxy Configuration',
    '# Generated by @acedergren/oci-genai-setup',
    '#',
    `# Region: ${config.region}`,
    '',
    '# OCI Configuration (used by the proxy)',
    `OCI_REGION="${config.region}"`,
    `OCI_COMPARTMENT_ID="${config.compartmentId}"`,
    `OCI_CONFIG_PROFILE="${config.profile}"`,
    '',
    '# Proxy Server Configuration',
    'OCI_ANTHROPIC_PROXY_PORT="8080"',
    'OCI_ANTHROPIC_PROXY_HOST="localhost"',
    '',
    '# Claude Code Configuration',
    '# Point Claude Code to the local proxy',
    'ANTHROPIC_API_URL="http://localhost:8080"',
    '',
    '# Model mapping (Claude -> OCI)',
    '# claude-3-opus-20240229      -> meta.llama-3.1-405b-instruct',
    '# claude-3-5-sonnet-20241022  -> xai.grok-3',
    '# claude-3-5-haiku-20241022   -> xai.grok-3-mini',
  ];

  return lines.join('\n') + '\n';
}

/**
 * Generate startup script for the proxy
 */
function generateStartupScript(config: GeneratedConfig): string {
  return `#!/bin/bash
# OCI Anthropic-Compatible Proxy Startup Script
# Generated by @acedergren/oci-genai-setup

# Load environment
source .env.oci-anthropic 2>/dev/null || true

# Start the proxy server
exec oci-anthropic-proxy \\
  --region "\${OCI_REGION:-${config.region}}" \\
  --compartment "\${OCI_COMPARTMENT_ID:-${config.compartmentId}}" \\
  --profile "\${OCI_CONFIG_PROFILE:-${config.profile}}" \\
  --port "\${OCI_ANTHROPIC_PROXY_PORT:-8080}" \\
  --host "\${OCI_ANTHROPIC_PROXY_HOST:-localhost}" \\
  "$@"
`;
}

/**
 * Generate usage instructions
 */
function generateReadme(config: GeneratedConfig): string {
  return `# OCI Anthropic-Compatible Proxy

This proxy enables Claude Code to use OCI GenAI models as a backend.

## Quick Start

1. **Install the proxy:**
   \`\`\`bash
   pnpm add -g @acedergren/oci-anthropic-compatible
   \`\`\`

2. **Start the proxy:**
   \`\`\`bash
   # Using the generated script
   ./start-oci-proxy.sh

   # Or directly with environment variables
   source .env.oci-anthropic
   oci-anthropic-proxy
   \`\`\`

3. **Configure Claude Code:**
   \`\`\`bash
   export ANTHROPIC_API_URL="http://localhost:8080"
   claude
   \`\`\`

## Model Mapping

| Claude Model | OCI Model |
|-------------|-----------|
| claude-3-opus-20240229 | meta.llama-3.1-405b-instruct |
| claude-3-sonnet-20240229 | meta.llama-3.3-70b-instruct |
| claude-3-haiku-20240307 | meta.llama-3.1-70b-instruct |
| claude-3-5-sonnet-20241022 | xai.grok-3 |
| claude-3-5-haiku-20241022 | xai.grok-3-mini |

You can also use OCI model names directly (e.g., \`grok-3\`, \`llama-3.3-70b\`).

## Configuration

| Variable | Description | Default |
|----------|-------------|---------|
| OCI_REGION | OCI region | ${config.region} |
| OCI_COMPARTMENT_ID | Compartment OCID | (required) |
| OCI_CONFIG_PROFILE | OCI config profile | ${config.profile} |
| OCI_ANTHROPIC_PROXY_PORT | Proxy port | 8080 |
| OCI_ANTHROPIC_PROXY_HOST | Proxy host | localhost |

## Files Generated

- \`.env.oci-anthropic\` - Environment variables
- \`start-oci-proxy.sh\` - Startup script
- \`ANTHROPIC_PROXY_README.md\` - This file
`;
}

/**
 * Write Anthropic-compatible configuration
 */
export async function writeAnthropicCompatConfig(
  config: GeneratedConfig,
  log: Logger
): Promise<{ success: boolean; path: string }> {
  const envPath = '.env.oci-anthropic';
  const scriptPath = 'start-oci-proxy.sh';
  const readmePath = 'ANTHROPIC_PROXY_README.md';

  try {
    // Write env file
    const envContent = generateEnvContent(config);
    await writeTextFile(envPath, envContent);

    // Write startup script (executable)
    const scriptContent = generateStartupScript(config);
    await writeTextFile(scriptPath, scriptContent, { mode: 0o755 });

    // Write usage readme
    const readmeContent = generateReadme(config);
    await writeTextFile(readmePath, readmeContent);

    return { success: true, path: envPath };
  } catch (error) {
    log.error(
      `Failed to write Anthropic-compatible config: ${error instanceof Error ? error.message : 'Unknown error'}`
    );
    return { success: false, path: envPath };
  }
}
