/**
 * Environment variable configuration generator
 *
 * Generates .env file or shell export commands
 */

import type { GeneratedConfig, Logger } from '../types.js';
import { fileExists, readTextFile, writeTextFile } from '../utils/file.js';

/**
 * Generate environment variables as key=value pairs
 */
export function generateEnvConfig(config: GeneratedConfig): string {
  const lines: string[] = [
    '# OCI GenAI Provider Configuration',
    '# Generated by @acedergren/oci-genai-setup',
    '',
    `OCI_CONFIG_PROFILE=${config.profile}`,
    `OCI_COMPARTMENT_ID=${config.compartmentId}`,
    `OCI_REGION=${config.region}`,
    '',
    '# Selected models (comma-separated)',
    `OCI_GENAI_MODELS=${config.models.join(',')}`,
  ];

  if (config.codingOptimized) {
    lines.push('', '# Coding optimization settings');
    lines.push('OCI_GENAI_TEMPERATURE=0.2');
    lines.push('OCI_GENAI_MAX_TOKENS=8192');
    lines.push('OCI_GENAI_FREQUENCY_PENALTY=0.1');
  }

  return lines.join('\n') + '\n';
}

/**
 * Generate shell export commands
 */
export function generateShellExports(config: GeneratedConfig): string {
  const lines: string[] = [
    '# OCI GenAI Provider Configuration',
    '# Add these to your ~/.bashrc, ~/.zshrc, or shell profile',
    '',
    `export OCI_CONFIG_PROFILE="${config.profile}"`,
    `export OCI_COMPARTMENT_ID="${config.compartmentId}"`,
    `export OCI_REGION="${config.region}"`,
  ];

  if (config.codingOptimized) {
    lines.push('');
    lines.push('# Coding optimization settings (optional)');
    lines.push('export OCI_GENAI_TEMPERATURE="0.2"');
    lines.push('export OCI_GENAI_MAX_TOKENS="8192"');
    lines.push('export OCI_GENAI_FREQUENCY_PENALTY="0.1"');
  }

  return lines.join('\n') + '\n';
}

/**
 * Merge new env vars with existing .env content
 */
function mergeEnvContent(existing: string, newContent: string): string {
  const existingLines = existing.split('\n');
  const newLines = newContent.split('\n');

  // Parse new env vars (skip comments and empty lines)
  const newVars = new Map<string, string>();
  for (const line of newLines) {
    const match = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
    if (match && match[1] && match[2] !== undefined) {
      newVars.set(match[1], match[2]);
    }
  }

  // Update existing lines or add new ones
  const updatedVars = new Set<string>();
  const result: string[] = [];

  for (const line of existingLines) {
    const match = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
    if (match && match[1] && newVars.has(match[1])) {
      // Update existing var - we know the key exists since we just checked
      const key = match[1];
      const value = newVars.get(key)!;
      result.push(`${key}=${value}`);
      updatedVars.add(key);
    } else {
      result.push(line);
    }
  }

  // Add any new vars that weren't in the existing file
  const toAdd: string[] = [];
  for (const [key, value] of newVars) {
    if (!updatedVars.has(key)) {
      toAdd.push(`${key}=${value}`);
    }
  }

  if (toAdd.length > 0) {
    result.push('');
    result.push('# OCI GenAI (added by oci-genai-setup)');
    result.push(...toAdd);
  }

  return result.join('\n');
}

/**
 * Write environment configuration to .env file
 */
export async function writeEnvConfig(
  config: GeneratedConfig,
  outputPath: string,
  log: Logger
): Promise<{ success: boolean; path: string }> {
  try {
    const newContent = generateEnvConfig(config);

    // If file exists, merge with existing content
    if (await fileExists(outputPath)) {
      const existing = await readTextFile(outputPath);
      const merged = mergeEnvContent(existing, newContent);
      await writeTextFile(outputPath, merged);
    } else {
      await writeTextFile(outputPath, newContent);
    }

    return { success: true, path: outputPath };
  } catch (error) {
    log.error(
      `Failed to write .env file: ${error instanceof Error ? error.message : 'Unknown error'}`
    );
    return { success: false, path: outputPath };
  }
}
