/**
 * OpenAI-compatible configuration generator
 *
 * Generates configuration for using OCI GenAI with OpenAI-compatible clients.
 * This enables drop-in replacement for OpenAI SDK usage.
 */

import type { GeneratedConfig, Logger } from '../types.js';
import { writeTextFile } from '../utils/file.js';

/**
 * OpenAI-compatible endpoint configuration
 */
interface OpenAICompatConfig {
  baseUrl: string;
  region: string;
  compartmentId: string;
  models: string[];
}

/**
 * Region to OpenAI-compatible endpoint mapping
 */
const OPENAI_COMPAT_ENDPOINTS: Record<string, string> = {
  'us-ashburn-1':
    'https://inference.generativeai.us-ashburn-1.oci.oraclecloud.com/20231130/actions/chat',
  'us-chicago-1':
    'https://inference.generativeai.us-chicago-1.oci.oraclecloud.com/20231130/actions/chat',
  'us-phoenix-1':
    'https://inference.generativeai.us-phoenix-1.oci.oraclecloud.com/20231130/actions/chat',
  'eu-frankfurt-1':
    'https://inference.generativeai.eu-frankfurt-1.oci.oraclecloud.com/20231130/actions/chat',
  'ap-hyderabad-1':
    'https://inference.generativeai.ap-hyderabad-1.oci.oraclecloud.com/20231130/actions/chat',
  'ap-osaka-1':
    'https://inference.generativeai.ap-osaka-1.oci.oraclecloud.com/20231130/actions/chat',
};

/**
 * Check if region supports OpenAI-compatible endpoints
 */
export function supportsOpenAICompat(region: string): boolean {
  return region in OPENAI_COMPAT_ENDPOINTS;
}

/**
 * Generate OpenAI-compatible configuration
 */
export function generateOpenAICompatConfig(config: GeneratedConfig): OpenAICompatConfig {
  const endpoint = OPENAI_COMPAT_ENDPOINTS[config.region];

  return {
    baseUrl:
      endpoint ||
      `https://inference.generativeai.${config.region}.oci.oraclecloud.com/20231130/actions/chat`,
    region: config.region,
    compartmentId: config.compartmentId,
    models: config.models,
  };
}

/**
 * Generate environment variables content for OpenAI-compatible usage
 */
function generateEnvContent(config: GeneratedConfig): string {
  const openaiConfig = generateOpenAICompatConfig(config);
  const supportsCompat = supportsOpenAICompat(config.region);

  const lines: string[] = [
    '# OCI GenAI - OpenAI Compatible Configuration',
    '# Generated by @acedergren/oci-genai-setup',
    '#',
    `# Region: ${config.region}${supportsCompat ? ' (OpenAI-compatible supported)' : ' (use native provider)'}`,
    '',
    '# OCI Configuration',
    `OCI_REGION="${config.region}"`,
    `OCI_COMPARTMENT_ID="${config.compartmentId}"`,
    `OCI_CONFIG_PROFILE="${config.profile}"`,
    '',
    '# OpenAI SDK Compatibility',
    `OPENAI_BASE_URL="${openaiConfig.baseUrl}"`,
    '# Note: Set OCI_API_KEY for API key auth, or use instance/resource principal',
    '',
    '# Available models (use with OpenAI SDK)',
    `# ${config.models.slice(0, 5).join(', ')}${config.models.length > 5 ? '...' : ''}`,
  ];

  return lines.join('\n') + '\n';
}

/**
 * Generate usage example script
 */
function generateUsageScript(config: GeneratedConfig): string {
  const model = config.models[0] || 'meta.llama-3.3-70b-instruct';

  return `#!/usr/bin/env node
/**
 * OCI GenAI - OpenAI Compatible Example
 *
 * Usage:
 *   1. Source the .env file: source .env.oci-openai
 *   2. Run: node oci-openai-example.mjs
 *
 * Or use with @acedergren/oci-openai-compatible:
 *   pnpm add @acedergren/oci-openai-compatible
 */

import { createOCIOpenAI } from '@acedergren/oci-openai-compatible';

const client = createOCIOpenAI({
  region: '${config.region}',
  compartmentId: process.env.OCI_COMPARTMENT_ID,
  // apiKey: process.env.OCI_API_KEY, // Optional for API key auth
});

const response = await client.chat.completions.create({
  model: '${model}',
  messages: [
    { role: 'system', content: 'You are a helpful assistant.' },
    { role: 'user', content: 'Hello! What can you help me with?' },
  ],
});

console.log(response.choices[0].message.content);
`;
}

/**
 * Write OpenAI-compatible configuration
 */
export async function writeOpenAICompatConfig(
  config: GeneratedConfig,
  log: Logger
): Promise<{ success: boolean; path: string }> {
  const envPath = '.env.oci-openai';
  const examplePath = 'oci-openai-example.mjs';

  try {
    // Check if region supports OpenAI-compatible endpoints
    if (!supportsOpenAICompat(config.region)) {
      log.warn(`Note: Region ${config.region} may not support OpenAI-compatible endpoints.`);
      log.warn('Consider using @acedergren/oci-genai-provider for full region support.\n');
    }

    // Write env file
    const envContent = generateEnvContent(config);
    await writeTextFile(envPath, envContent);

    // Write example script
    const exampleContent = generateUsageScript(config);
    await writeTextFile(examplePath, exampleContent);

    return { success: true, path: envPath };
  } catch (error) {
    log.error(
      `Failed to write OpenAI-compatible config: ${error instanceof Error ? error.message : 'Unknown error'}`
    );
    return { success: false, path: envPath };
  }
}
