import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/cli.ts'],
  format: ['esm'],
  clean: true,
  bundle: true,
  noExternal: [
    '@acedergren/oci-genai-provider',
    '@opentui/react',
    '@opentui/core',
    'yoga-layout-prebuilt',
    'ai',
    'pino',
    'commander',
    'inquirer',
    'chalk',
    'eventsource-parser',
    'oci-common',
    'oci-generativeaiinference',
    'oci-aispeech',
    'oci-identity',
    'oci-objectstorage',
    'zod',
  ],
  minify: true,
  sourcemap: false,
  target: 'node20',
  shims: true,
});
